version: "3"

# sui-chan is made by following command
# $ docker build -t suichan:latest .

services:
    suichan:
        image: suichan:latest
        tty: true
        restart: unless-stopped
        volumes:
            - ./data:/usr/src/app/data:rw
